# Generated by Django 5.2.13 on 2026-04-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_category_icon_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixedExpense',
        ),
    ]
