# Generated by Django 5.2.13 on 2026-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_delete_fixedexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='need_or_want',
            field=models.CharField(choices=[('need', 'Need'), ('want', 'Want')], default='want', max_length=10),
        ),
    ]
