# Generated by Django 5.2.13 on 2026-04-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_category_need_or_want'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_surplus_policy',
            field=models.CharField(choices=[('carryover', 'Carry over to next day budget'), ('save', 'Move surplus to savings')], default='carryover', max_length=15),
        ),
    ]
