# Generated by Django 5.2.13 on 2026-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_add_profile_monthly_income_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
